Non-profit description
VandyHacks/vh-hacker-guide pull request #11
Opened 2020-06-27 22:29 UTC by saydus

Added the non-profit description to the hacker guide.

2020-07-04 17:42 UTC, gfting approved these changes

2020-07-04 17:43 UTC, gfting commented
@saydus Please resolve the merge conflicts and then I'll merge it in.

2020-07-06 03:07 UTC, gfting requested changes
One last thing–just remove the .DS_Store values and it'll be great.

2020-07-06 03:16 UTC, saydus commented
Sorry, thought .gitignore change would take care of it.

2020-07-06 03:32 UTC, merged